package com.eventflow.utils;

public enum ErrorCode {
  FIELD_REQUIRED,
  INVALID_FORMAT,
  INVALID_CREDENTIALS,
  AUTHENTICATION_REQUIRED,
  RESOURCE_NOT_FOUND,
  DATE_RANGE_INVALID,
  ENUM_INVALID,
  EMAIL_ALREADY_EXISTS,
  ROLE_FORBIDDEN,
  DUPLICATE_REGISTRATION,
  CHECKIN_WINDOW_CLOSED,
  TASK_DEPENDENCY_CYCLE,
  TASK_ASSIGNMENT_INVALID,
  SESSION_EXPIRED,
  RESOURCE_CONFLICT
}